<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/01/12 16:10:11
sfConfig::add(array(
  'app_sf_guard_plugin_profile_class' => 'UserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
));
