<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/01/18 10:01:08
sfConfig::add(array(
  'app_sf_guard_plugin_profile_class' => 'UserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
));
