<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/14 10:47:54

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=pcc;host=localhost',
  'username' => 'root',
  'password' => 'alfilasesino',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
