<?php

/**
 * Base class that represents a row from the 'producto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jan 12 14:28:40 2010
 *
 * @package    lib.model.om
 */
abstract class BaseProducto extends BaseObject  implements Persistent {


  const PEER = 'ProductoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProductoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the codigo field.
	 * @var        string
	 */
	protected $codigo;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the marca field.
	 * @var        string
	 */
	protected $marca;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the producto_categoria_id field.
	 * @var        int
	 */
	protected $producto_categoria_id;

	/**
	 * The value for the producto_udm_id field.
	 * @var        int
	 */
	protected $producto_udm_id;

	/**
	 * The value for the ubicacion_fisica field.
	 * @var        string
	 */
	protected $ubicacion_fisica;

	/**
	 * The value for the stock_actual field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock_actual;

	/**
	 * The value for the stock_reservado field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock_reservado;

	/**
	 * The value for the stock_preaviso field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock_preaviso;

	/**
	 * The value for the stock_critico field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $stock_critico;

	/**
	 * @var        ProductoCategoria
	 */
	protected $aProductoCategoria;

	/**
	 * @var        ProductoUDM
	 */
	protected $aProductoUDM;

	/**
	 * @var        array Evento[] Collection to store aggregation of Evento objects.
	 */
	protected $collEventos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEventos.
	 */
	private $lastEventoCriteria = null;

	/**
	 * @var        array Compra[] Collection to store aggregation of Compra objects.
	 */
	protected $collCompras;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCompras.
	 */
	private $lastCompraCriteria = null;

	/**
	 * @var        array Venta[] Collection to store aggregation of Venta objects.
	 */
	protected $collVentas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVentas.
	 */
	private $lastVentaCriteria = null;

	/**
	 * @var        array ProductoArchivo[] Collection to store aggregation of ProductoArchivo objects.
	 */
	protected $collProductoArchivos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProductoArchivos.
	 */
	private $lastProductoArchivoCriteria = null;

	/**
	 * @var        array ProductoProveedor[] Collection to store aggregation of ProductoProveedor objects.
	 */
	protected $collProductoProveedors;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProductoProveedors.
	 */
	private $lastProductoProveedorCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseProducto object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->stock_actual = 0;
		$this->stock_reservado = 0;
		$this->stock_preaviso = 0;
		$this->stock_critico = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [codigo] column value.
	 * Codigo del Producto (20)
	 * @return     string
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [nombre] column value.
	 * Nombre del Producto (100)
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [marca] column value.
	 * Marca del Producto (80)
	 * @return     string
	 */
	public function getMarca()
	{
		return $this->marca;
	}

	/**
	 * Get the [descripcion] column value.
	 * Descripcion del Producto
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [producto_categoria_id] column value.
	 * Refrencia la categoria del producto
	 * @return     int
	 */
	public function getProductoCategoriaId()
	{
		return $this->producto_categoria_id;
	}

	/**
	 * Get the [producto_udm_id] column value.
	 * Unidad de Medida
	 * @return     int
	 */
	public function getProductoUdmId()
	{
		return $this->producto_udm_id;
	}

	/**
	 * Get the [ubicacion_fisica] column value.
	 * 
	 * @return     string
	 */
	public function getUbicacionFisica()
	{
		return $this->ubicacion_fisica;
	}

	/**
	 * Get the [stock_actual] column value.
	 * 
	 * @return     int
	 */
	public function getStockActual()
	{
		return $this->stock_actual;
	}

	/**
	 * Get the [stock_reservado] column value.
	 * 
	 * @return     int
	 */
	public function getStockReservado()
	{
		return $this->stock_reservado;
	}

	/**
	 * Get the [stock_preaviso] column value.
	 * 
	 * @return     int
	 */
	public function getStockPreaviso()
	{
		return $this->stock_preaviso;
	}

	/**
	 * Get the [stock_critico] column value.
	 * 
	 * @return     int
	 */
	public function getStockCritico()
	{
		return $this->stock_critico;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ProductoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [codigo] column.
	 * Codigo del Producto (20)
	 * @param      string $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = ProductoPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Set the value of [nombre] column.
	 * Nombre del Producto (100)
	 * @param      string $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = ProductoPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [marca] column.
	 * Marca del Producto (80)
	 * @param      string $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setMarca($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->marca !== $v) {
			$this->marca = $v;
			$this->modifiedColumns[] = ProductoPeer::MARCA;
		}

		return $this;
	} // setMarca()

	/**
	 * Set the value of [descripcion] column.
	 * Descripcion del Producto
	 * @param      string $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = ProductoPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [producto_categoria_id] column.
	 * Refrencia la categoria del producto
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setProductoCategoriaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->producto_categoria_id !== $v) {
			$this->producto_categoria_id = $v;
			$this->modifiedColumns[] = ProductoPeer::PRODUCTO_CATEGORIA_ID;
		}

		if ($this->aProductoCategoria !== null && $this->aProductoCategoria->getId() !== $v) {
			$this->aProductoCategoria = null;
		}

		return $this;
	} // setProductoCategoriaId()

	/**
	 * Set the value of [producto_udm_id] column.
	 * Unidad de Medida
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setProductoUdmId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->producto_udm_id !== $v) {
			$this->producto_udm_id = $v;
			$this->modifiedColumns[] = ProductoPeer::PRODUCTO_UDM_ID;
		}

		if ($this->aProductoUDM !== null && $this->aProductoUDM->getId() !== $v) {
			$this->aProductoUDM = null;
		}

		return $this;
	} // setProductoUdmId()

	/**
	 * Set the value of [ubicacion_fisica] column.
	 * 
	 * @param      string $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setUbicacionFisica($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ubicacion_fisica !== $v) {
			$this->ubicacion_fisica = $v;
			$this->modifiedColumns[] = ProductoPeer::UBICACION_FISICA;
		}

		return $this;
	} // setUbicacionFisica()

	/**
	 * Set the value of [stock_actual] column.
	 * 
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setStockActual($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock_actual !== $v || $v === 0) {
			$this->stock_actual = $v;
			$this->modifiedColumns[] = ProductoPeer::STOCK_ACTUAL;
		}

		return $this;
	} // setStockActual()

	/**
	 * Set the value of [stock_reservado] column.
	 * 
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setStockReservado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock_reservado !== $v || $v === 0) {
			$this->stock_reservado = $v;
			$this->modifiedColumns[] = ProductoPeer::STOCK_RESERVADO;
		}

		return $this;
	} // setStockReservado()

	/**
	 * Set the value of [stock_preaviso] column.
	 * 
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setStockPreaviso($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock_preaviso !== $v || $v === 0) {
			$this->stock_preaviso = $v;
			$this->modifiedColumns[] = ProductoPeer::STOCK_PREAVISO;
		}

		return $this;
	} // setStockPreaviso()

	/**
	 * Set the value of [stock_critico] column.
	 * 
	 * @param      int $v new value
	 * @return     Producto The current object (for fluent API support)
	 */
	public function setStockCritico($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock_critico !== $v || $v === 0) {
			$this->stock_critico = $v;
			$this->modifiedColumns[] = ProductoPeer::STOCK_CRITICO;
		}

		return $this;
	} // setStockCritico()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ProductoPeer::STOCK_ACTUAL,ProductoPeer::STOCK_RESERVADO,ProductoPeer::STOCK_PREAVISO,ProductoPeer::STOCK_CRITICO))) {
				return false;
			}

			if ($this->stock_actual !== 0) {
				return false;
			}

			if ($this->stock_reservado !== 0) {
				return false;
			}

			if ($this->stock_preaviso !== 0) {
				return false;
			}

			if ($this->stock_critico !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->codigo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->nombre = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->marca = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->descripcion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->producto_categoria_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->producto_udm_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->ubicacion_fisica = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->stock_actual = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->stock_reservado = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->stock_preaviso = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->stock_critico = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = ProductoPeer::NUM_COLUMNS - ProductoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Producto object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aProductoCategoria !== null && $this->producto_categoria_id !== $this->aProductoCategoria->getId()) {
			$this->aProductoCategoria = null;
		}
		if ($this->aProductoUDM !== null && $this->producto_udm_id !== $this->aProductoUDM->getId()) {
			$this->aProductoUDM = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ProductoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aProductoCategoria = null;
			$this->aProductoUDM = null;
			$this->collEventos = null;
			$this->lastEventoCriteria = null;

			$this->collCompras = null;
			$this->lastCompraCriteria = null;

			$this->collVentas = null;
			$this->lastVentaCriteria = null;

			$this->collProductoArchivos = null;
			$this->lastProductoArchivoCriteria = null;

			$this->collProductoProveedors = null;
			$this->lastProductoProveedorCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProducto:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ProductoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseProducto:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProducto:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseProducto:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ProductoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProductoCategoria !== null) {
				if ($this->aProductoCategoria->isModified() || $this->aProductoCategoria->isNew()) {
					$affectedRows += $this->aProductoCategoria->save($con);
				}
				$this->setProductoCategoria($this->aProductoCategoria);
			}

			if ($this->aProductoUDM !== null) {
				if ($this->aProductoUDM->isModified() || $this->aProductoUDM->isNew()) {
					$affectedRows += $this->aProductoUDM->save($con);
				}
				$this->setProductoUDM($this->aProductoUDM);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ProductoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProductoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProductoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEventos !== null) {
				foreach ($this->collEventos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCompras !== null) {
				foreach ($this->collCompras as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVentas !== null) {
				foreach ($this->collVentas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProductoArchivos !== null) {
				foreach ($this->collProductoArchivos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProductoProveedors !== null) {
				foreach ($this->collProductoProveedors as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProductoCategoria !== null) {
				if (!$this->aProductoCategoria->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProductoCategoria->getValidationFailures());
				}
			}

			if ($this->aProductoUDM !== null) {
				if (!$this->aProductoUDM->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProductoUDM->getValidationFailures());
				}
			}


			if (($retval = ProductoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEventos !== null) {
					foreach ($this->collEventos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCompras !== null) {
					foreach ($this->collCompras as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVentas !== null) {
					foreach ($this->collVentas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProductoArchivos !== null) {
					foreach ($this->collProductoArchivos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProductoProveedors !== null) {
					foreach ($this->collProductoProveedors as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProductoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCodigo();
				break;
			case 2:
				return $this->getNombre();
				break;
			case 3:
				return $this->getMarca();
				break;
			case 4:
				return $this->getDescripcion();
				break;
			case 5:
				return $this->getProductoCategoriaId();
				break;
			case 6:
				return $this->getProductoUdmId();
				break;
			case 7:
				return $this->getUbicacionFisica();
				break;
			case 8:
				return $this->getStockActual();
				break;
			case 9:
				return $this->getStockReservado();
				break;
			case 10:
				return $this->getStockPreaviso();
				break;
			case 11:
				return $this->getStockCritico();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ProductoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCodigo(),
			$keys[2] => $this->getNombre(),
			$keys[3] => $this->getMarca(),
			$keys[4] => $this->getDescripcion(),
			$keys[5] => $this->getProductoCategoriaId(),
			$keys[6] => $this->getProductoUdmId(),
			$keys[7] => $this->getUbicacionFisica(),
			$keys[8] => $this->getStockActual(),
			$keys[9] => $this->getStockReservado(),
			$keys[10] => $this->getStockPreaviso(),
			$keys[11] => $this->getStockCritico(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProductoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCodigo($value);
				break;
			case 2:
				$this->setNombre($value);
				break;
			case 3:
				$this->setMarca($value);
				break;
			case 4:
				$this->setDescripcion($value);
				break;
			case 5:
				$this->setProductoCategoriaId($value);
				break;
			case 6:
				$this->setProductoUdmId($value);
				break;
			case 7:
				$this->setUbicacionFisica($value);
				break;
			case 8:
				$this->setStockActual($value);
				break;
			case 9:
				$this->setStockReservado($value);
				break;
			case 10:
				$this->setStockPreaviso($value);
				break;
			case 11:
				$this->setStockCritico($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ProductoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCodigo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNombre($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setMarca($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDescripcion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setProductoCategoriaId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setProductoUdmId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUbicacionFisica($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setStockActual($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStockReservado($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setStockPreaviso($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setStockCritico($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProductoPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProductoPeer::ID)) $criteria->add(ProductoPeer::ID, $this->id);
		if ($this->isColumnModified(ProductoPeer::CODIGO)) $criteria->add(ProductoPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(ProductoPeer::NOMBRE)) $criteria->add(ProductoPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(ProductoPeer::MARCA)) $criteria->add(ProductoPeer::MARCA, $this->marca);
		if ($this->isColumnModified(ProductoPeer::DESCRIPCION)) $criteria->add(ProductoPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(ProductoPeer::PRODUCTO_CATEGORIA_ID)) $criteria->add(ProductoPeer::PRODUCTO_CATEGORIA_ID, $this->producto_categoria_id);
		if ($this->isColumnModified(ProductoPeer::PRODUCTO_UDM_ID)) $criteria->add(ProductoPeer::PRODUCTO_UDM_ID, $this->producto_udm_id);
		if ($this->isColumnModified(ProductoPeer::UBICACION_FISICA)) $criteria->add(ProductoPeer::UBICACION_FISICA, $this->ubicacion_fisica);
		if ($this->isColumnModified(ProductoPeer::STOCK_ACTUAL)) $criteria->add(ProductoPeer::STOCK_ACTUAL, $this->stock_actual);
		if ($this->isColumnModified(ProductoPeer::STOCK_RESERVADO)) $criteria->add(ProductoPeer::STOCK_RESERVADO, $this->stock_reservado);
		if ($this->isColumnModified(ProductoPeer::STOCK_PREAVISO)) $criteria->add(ProductoPeer::STOCK_PREAVISO, $this->stock_preaviso);
		if ($this->isColumnModified(ProductoPeer::STOCK_CRITICO)) $criteria->add(ProductoPeer::STOCK_CRITICO, $this->stock_critico);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProductoPeer::DATABASE_NAME);

		$criteria->add(ProductoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Producto (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCodigo($this->codigo);

		$copyObj->setNombre($this->nombre);

		$copyObj->setMarca($this->marca);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setProductoCategoriaId($this->producto_categoria_id);

		$copyObj->setProductoUdmId($this->producto_udm_id);

		$copyObj->setUbicacionFisica($this->ubicacion_fisica);

		$copyObj->setStockActual($this->stock_actual);

		$copyObj->setStockReservado($this->stock_reservado);

		$copyObj->setStockPreaviso($this->stock_preaviso);

		$copyObj->setStockCritico($this->stock_critico);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEventos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEvento($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCompras() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCompra($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVentas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVenta($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getProductoArchivos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProductoArchivo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getProductoProveedors() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProductoProveedor($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Producto Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProductoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProductoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ProductoCategoria object.
	 *
	 * @param      ProductoCategoria $v
	 * @return     Producto The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProductoCategoria(ProductoCategoria $v = null)
	{
		if ($v === null) {
			$this->setProductoCategoriaId(NULL);
		} else {
			$this->setProductoCategoriaId($v->getId());
		}

		$this->aProductoCategoria = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ProductoCategoria object, it will not be re-added.
		if ($v !== null) {
			$v->addProducto($this);
		}

		return $this;
	}


	/**
	 * Get the associated ProductoCategoria object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ProductoCategoria The associated ProductoCategoria object.
	 * @throws     PropelException
	 */
	public function getProductoCategoria(PropelPDO $con = null)
	{
		if ($this->aProductoCategoria === null && ($this->producto_categoria_id !== null)) {
			$c = new Criteria(ProductoCategoriaPeer::DATABASE_NAME);
			$c->add(ProductoCategoriaPeer::ID, $this->producto_categoria_id);
			$this->aProductoCategoria = ProductoCategoriaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProductoCategoria->addProductos($this);
			 */
		}
		return $this->aProductoCategoria;
	}

	/**
	 * Declares an association between this object and a ProductoUDM object.
	 *
	 * @param      ProductoUDM $v
	 * @return     Producto The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProductoUDM(ProductoUDM $v = null)
	{
		if ($v === null) {
			$this->setProductoUdmId(NULL);
		} else {
			$this->setProductoUdmId($v->getId());
		}

		$this->aProductoUDM = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ProductoUDM object, it will not be re-added.
		if ($v !== null) {
			$v->addProducto($this);
		}

		return $this;
	}


	/**
	 * Get the associated ProductoUDM object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ProductoUDM The associated ProductoUDM object.
	 * @throws     PropelException
	 */
	public function getProductoUDM(PropelPDO $con = null)
	{
		if ($this->aProductoUDM === null && ($this->producto_udm_id !== null)) {
			$c = new Criteria(ProductoUDMPeer::DATABASE_NAME);
			$c->add(ProductoUDMPeer::ID, $this->producto_udm_id);
			$this->aProductoUDM = ProductoUDMPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProductoUDM->addProductos($this);
			 */
		}
		return $this->aProductoUDM;
	}

	/**
	 * Clears out the collEventos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEventos()
	 */
	public function clearEventos()
	{
		$this->collEventos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEventos collection (array).
	 *
	 * By default this just sets the collEventos collection to an empty array (like clearcollEventos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEventos()
	{
		$this->collEventos = array();
	}

	/**
	 * Gets an array of Evento objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Producto has previously been saved, it will retrieve
	 * related Eventos from storage. If this Producto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Evento[]
	 * @throws     PropelException
	 */
	public function getEventos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEventos === null) {
			if ($this->isNew()) {
			   $this->collEventos = array();
			} else {

				$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

				EventoPeer::addSelectColumns($criteria);
				$this->collEventos = EventoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

				EventoPeer::addSelectColumns($criteria);
				if (!isset($this->lastEventoCriteria) || !$this->lastEventoCriteria->equals($criteria)) {
					$this->collEventos = EventoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEventoCriteria = $criteria;
		return $this->collEventos;
	}

	/**
	 * Returns the number of related Evento objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Evento objects.
	 * @throws     PropelException
	 */
	public function countEventos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEventos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

				$count = EventoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

				if (!isset($this->lastEventoCriteria) || !$this->lastEventoCriteria->equals($criteria)) {
					$count = EventoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEventos);
				}
			} else {
				$count = count($this->collEventos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Evento object to this object
	 * through the Evento foreign key attribute.
	 *
	 * @param      Evento $l Evento
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEvento(Evento $l)
	{
		if ($this->collEventos === null) {
			$this->initEventos();
		}
		if (!in_array($l, $this->collEventos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEventos, $l);
			$l->setProducto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related Eventos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getEventosJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEventos === null) {
			if ($this->isNew()) {
				$this->collEventos = array();
			} else {

				$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

				$this->collEventos = EventoPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EventoPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastEventoCriteria) || !$this->lastEventoCriteria->equals($criteria)) {
				$this->collEventos = EventoPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastEventoCriteria = $criteria;

		return $this->collEventos;
	}

	/**
	 * Clears out the collCompras collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCompras()
	 */
	public function clearCompras()
	{
		$this->collCompras = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCompras collection (array).
	 *
	 * By default this just sets the collCompras collection to an empty array (like clearcollCompras());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCompras()
	{
		$this->collCompras = array();
	}

	/**
	 * Gets an array of Compra objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Producto has previously been saved, it will retrieve
	 * related Compras from storage. If this Producto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Compra[]
	 * @throws     PropelException
	 */
	public function getCompras($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompras === null) {
			if ($this->isNew()) {
			   $this->collCompras = array();
			} else {

				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				CompraPeer::addSelectColumns($criteria);
				$this->collCompras = CompraPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				CompraPeer::addSelectColumns($criteria);
				if (!isset($this->lastCompraCriteria) || !$this->lastCompraCriteria->equals($criteria)) {
					$this->collCompras = CompraPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCompraCriteria = $criteria;
		return $this->collCompras;
	}

	/**
	 * Returns the number of related Compra objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Compra objects.
	 * @throws     PropelException
	 */
	public function countCompras(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCompras === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				$count = CompraPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				if (!isset($this->lastCompraCriteria) || !$this->lastCompraCriteria->equals($criteria)) {
					$count = CompraPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCompras);
				}
			} else {
				$count = count($this->collCompras);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Compra object to this object
	 * through the Compra foreign key attribute.
	 *
	 * @param      Compra $l Compra
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCompra(Compra $l)
	{
		if ($this->collCompras === null) {
			$this->initCompras();
		}
		if (!in_array($l, $this->collCompras, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCompras, $l);
			$l->setProducto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related Compras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getComprasJoinProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompras === null) {
			if ($this->isNew()) {
				$this->collCompras = array();
			} else {

				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				$this->collCompras = CompraPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastCompraCriteria) || !$this->lastCompraCriteria->equals($criteria)) {
				$this->collCompras = CompraPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompraCriteria = $criteria;

		return $this->collCompras;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related Compras from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getComprasJoinNotaPedido($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompras === null) {
			if ($this->isNew()) {
				$this->collCompras = array();
			} else {

				$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

				$this->collCompras = CompraPeer::doSelectJoinNotaPedido($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompraPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastCompraCriteria) || !$this->lastCompraCriteria->equals($criteria)) {
				$this->collCompras = CompraPeer::doSelectJoinNotaPedido($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompraCriteria = $criteria;

		return $this->collCompras;
	}

	/**
	 * Clears out the collVentas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVentas()
	 */
	public function clearVentas()
	{
		$this->collVentas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVentas collection (array).
	 *
	 * By default this just sets the collVentas collection to an empty array (like clearcollVentas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVentas()
	{
		$this->collVentas = array();
	}

	/**
	 * Gets an array of Venta objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Producto has previously been saved, it will retrieve
	 * related Ventas from storage. If this Producto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Venta[]
	 * @throws     PropelException
	 */
	public function getVentas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentas === null) {
			if ($this->isNew()) {
			   $this->collVentas = array();
			} else {

				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				VentaPeer::addSelectColumns($criteria);
				$this->collVentas = VentaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				VentaPeer::addSelectColumns($criteria);
				if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
					$this->collVentas = VentaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVentaCriteria = $criteria;
		return $this->collVentas;
	}

	/**
	 * Returns the number of related Venta objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Venta objects.
	 * @throws     PropelException
	 */
	public function countVentas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVentas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				$count = VentaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
					$count = VentaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collVentas);
				}
			} else {
				$count = count($this->collVentas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Venta object to this object
	 * through the Venta foreign key attribute.
	 *
	 * @param      Venta $l Venta
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVenta(Venta $l)
	{
		if ($this->collVentas === null) {
			$this->initVentas();
		}
		if (!in_array($l, $this->collVentas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVentas, $l);
			$l->setProducto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related Ventas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getVentasJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentas === null) {
			if ($this->isNew()) {
				$this->collVentas = array();
			} else {

				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				$this->collVentas = VentaPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
				$this->collVentas = VentaPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastVentaCriteria = $criteria;

		return $this->collVentas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related Ventas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getVentasJoinProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentas === null) {
			if ($this->isNew()) {
				$this->collVentas = array();
			} else {

				$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

				$this->collVentas = VentaPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VentaPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
				$this->collVentas = VentaPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastVentaCriteria = $criteria;

		return $this->collVentas;
	}

	/**
	 * Clears out the collProductoArchivos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProductoArchivos()
	 */
	public function clearProductoArchivos()
	{
		$this->collProductoArchivos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProductoArchivos collection (array).
	 *
	 * By default this just sets the collProductoArchivos collection to an empty array (like clearcollProductoArchivos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProductoArchivos()
	{
		$this->collProductoArchivos = array();
	}

	/**
	 * Gets an array of ProductoArchivo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Producto has previously been saved, it will retrieve
	 * related ProductoArchivos from storage. If this Producto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProductoArchivo[]
	 * @throws     PropelException
	 */
	public function getProductoArchivos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductoArchivos === null) {
			if ($this->isNew()) {
			   $this->collProductoArchivos = array();
			} else {

				$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

				ProductoArchivoPeer::addSelectColumns($criteria);
				$this->collProductoArchivos = ProductoArchivoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

				ProductoArchivoPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductoArchivoCriteria) || !$this->lastProductoArchivoCriteria->equals($criteria)) {
					$this->collProductoArchivos = ProductoArchivoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductoArchivoCriteria = $criteria;
		return $this->collProductoArchivos;
	}

	/**
	 * Returns the number of related ProductoArchivo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProductoArchivo objects.
	 * @throws     PropelException
	 */
	public function countProductoArchivos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProductoArchivos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

				$count = ProductoArchivoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

				if (!isset($this->lastProductoArchivoCriteria) || !$this->lastProductoArchivoCriteria->equals($criteria)) {
					$count = ProductoArchivoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProductoArchivos);
				}
			} else {
				$count = count($this->collProductoArchivos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProductoArchivo object to this object
	 * through the ProductoArchivo foreign key attribute.
	 *
	 * @param      ProductoArchivo $l ProductoArchivo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProductoArchivo(ProductoArchivo $l)
	{
		if ($this->collProductoArchivos === null) {
			$this->initProductoArchivos();
		}
		if (!in_array($l, $this->collProductoArchivos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProductoArchivos, $l);
			$l->setProducto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related ProductoArchivos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getProductoArchivosJoinArchivo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductoArchivos === null) {
			if ($this->isNew()) {
				$this->collProductoArchivos = array();
			} else {

				$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

				$this->collProductoArchivos = ProductoArchivoPeer::doSelectJoinArchivo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProductoArchivoPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastProductoArchivoCriteria) || !$this->lastProductoArchivoCriteria->equals($criteria)) {
				$this->collProductoArchivos = ProductoArchivoPeer::doSelectJoinArchivo($criteria, $con, $join_behavior);
			}
		}
		$this->lastProductoArchivoCriteria = $criteria;

		return $this->collProductoArchivos;
	}

	/**
	 * Clears out the collProductoProveedors collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProductoProveedors()
	 */
	public function clearProductoProveedors()
	{
		$this->collProductoProveedors = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProductoProveedors collection (array).
	 *
	 * By default this just sets the collProductoProveedors collection to an empty array (like clearcollProductoProveedors());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProductoProveedors()
	{
		$this->collProductoProveedors = array();
	}

	/**
	 * Gets an array of ProductoProveedor objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Producto has previously been saved, it will retrieve
	 * related ProductoProveedors from storage. If this Producto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProductoProveedor[]
	 * @throws     PropelException
	 */
	public function getProductoProveedors($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductoProveedors === null) {
			if ($this->isNew()) {
			   $this->collProductoProveedors = array();
			} else {

				$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

				ProductoProveedorPeer::addSelectColumns($criteria);
				$this->collProductoProveedors = ProductoProveedorPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

				ProductoProveedorPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductoProveedorCriteria) || !$this->lastProductoProveedorCriteria->equals($criteria)) {
					$this->collProductoProveedors = ProductoProveedorPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductoProveedorCriteria = $criteria;
		return $this->collProductoProveedors;
	}

	/**
	 * Returns the number of related ProductoProveedor objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProductoProveedor objects.
	 * @throws     PropelException
	 */
	public function countProductoProveedors(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProductoProveedors === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

				$count = ProductoProveedorPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

				if (!isset($this->lastProductoProveedorCriteria) || !$this->lastProductoProveedorCriteria->equals($criteria)) {
					$count = ProductoProveedorPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProductoProveedors);
				}
			} else {
				$count = count($this->collProductoProveedors);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProductoProveedor object to this object
	 * through the ProductoProveedor foreign key attribute.
	 *
	 * @param      ProductoProveedor $l ProductoProveedor
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProductoProveedor(ProductoProveedor $l)
	{
		if ($this->collProductoProveedors === null) {
			$this->initProductoProveedors();
		}
		if (!in_array($l, $this->collProductoProveedors, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProductoProveedors, $l);
			$l->setProducto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Producto is new, it will return
	 * an empty collection; or if this Producto has previously
	 * been saved, it will retrieve related ProductoProveedors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Producto.
	 */
	public function getProductoProveedorsJoinProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductoProveedors === null) {
			if ($this->isNew()) {
				$this->collProductoProveedors = array();
			} else {

				$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

				$this->collProductoProveedors = ProductoProveedorPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProductoProveedorPeer::PRODUCTO_ID, $this->id);

			if (!isset($this->lastProductoProveedorCriteria) || !$this->lastProductoProveedorCriteria->equals($criteria)) {
				$this->collProductoProveedors = ProductoProveedorPeer::doSelectJoinProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastProductoProveedorCriteria = $criteria;

		return $this->collProductoProveedors;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEventos) {
				foreach ((array) $this->collEventos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCompras) {
				foreach ((array) $this->collCompras as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVentas) {
				foreach ((array) $this->collVentas as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collProductoArchivos) {
				foreach ((array) $this->collProductoArchivos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collProductoProveedors) {
				foreach ((array) $this->collProductoProveedors as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEventos = null;
		$this->collCompras = null;
		$this->collVentas = null;
		$this->collProductoArchivos = null;
		$this->collProductoProveedors = null;
			$this->aProductoCategoria = null;
			$this->aProductoUDM = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseProducto:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseProducto::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseProducto
