<?php

/**
 * Base class that represents a row from the 'user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jan 12 14:28:40 2010
 *
 * @package    lib.model.om
 */
abstract class BaseUserProfile extends BaseObject  implements Persistent {


  const PEER = 'UserProfilePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserProfilePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the language field.
	 * Note: this column has a database default value of: 'es'
	 * @var        string
	 */
	protected $language;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the apellido field.
	 * @var        string
	 */
	protected $apellido;

	/**
	 * The value for the fdn field.
	 * @var        string
	 */
	protected $fdn;

	/**
	 * The value for the nacionalidad field.
	 * @var        int
	 */
	protected $nacionalidad;

	/**
	 * The value for the documento_tipo field.
	 * @var        int
	 */
	protected $documento_tipo;

	/**
	 * The value for the documento_numero field.
	 * @var        string
	 */
	protected $documento_numero;

	/**
	 * The value for the cuil field.
	 * @var        string
	 */
	protected $cuil;

	/**
	 * The value for the legajo field.
	 * @var        string
	 */
	protected $legajo;

	/**
	 * The value for the telefono field.
	 * @var        string
	 */
	protected $telefono;

	/**
	 * The value for the movil field.
	 * @var        string
	 */
	protected $movil;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the domicilio_calle field.
	 * @var        string
	 */
	protected $domicilio_calle;

	/**
	 * The value for the domicilio_numero field.
	 * @var        string
	 */
	protected $domicilio_numero;

	/**
	 * The value for the domicilio_manzana field.
	 * @var        string
	 */
	protected $domicilio_manzana;

	/**
	 * The value for the domicilio_barrio field.
	 * @var        string
	 */
	protected $domicilio_barrio;

	/**
	 * The value for the domicilio_piso field.
	 * @var        string
	 */
	protected $domicilio_piso;

	/**
	 * The value for the domicilio_depto field.
	 * @var        string
	 */
	protected $domicilio_depto;

	/**
	 * The value for the localidad_id field.
	 * @var        int
	 */
	protected $localidad_id;

	/**
	 * The value for the provincia_id field.
	 * @var        int
	 */
	protected $provincia_id;

	/**
	 * The value for the comentario field.
	 * @var        string
	 */
	protected $comentario;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * @var        Pais
	 */
	protected $aPais;

	/**
	 * @var        Localidad
	 */
	protected $aLocalidad;

	/**
	 * @var        Provincia
	 */
	protected $aProvincia;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUserProfile object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->language = 'es';
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [language] column value.
	 * Lenguaje nativo del usuario
	 * @return     string
	 */
	public function getLanguage()
	{
		return $this->language;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [apellido] column value.
	 * 
	 * @return     string
	 */
	public function getApellido()
	{
		return $this->apellido;
	}

	/**
	 * Get the [optionally formatted] temporal [fdn] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFdn($format = 'Y-m-d')
	{
		if ($this->fdn === null) {
			return null;
		}


		if ($this->fdn === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fdn);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fdn, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [nacionalidad] column value.
	 * 
	 * @return     int
	 */
	public function getNacionalidad()
	{
		return $this->nacionalidad;
	}

	/**
	 * Get the [documento_tipo] column value.
	 * 
	 * @return     int
	 */
	public function getDocumentoTipo()
	{
		return $this->documento_tipo;
	}

	/**
	 * Get the [documento_numero] column value.
	 * 
	 * @return     string
	 */
	public function getDocumentoNumero()
	{
		return $this->documento_numero;
	}

	/**
	 * Get the [cuil] column value.
	 * 
	 * @return     string
	 */
	public function getCuil()
	{
		return $this->cuil;
	}

	/**
	 * Get the [legajo] column value.
	 * 
	 * @return     string
	 */
	public function getLegajo()
	{
		return $this->legajo;
	}

	/**
	 * Get the [telefono] column value.
	 * Telefono fijo del usuario
	 * @return     string
	 */
	public function getTelefono()
	{
		return $this->telefono;
	}

	/**
	 * Get the [movil] column value.
	 * 
	 * @return     string
	 */
	public function getMovil()
	{
		return $this->movil;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [domicilio_calle] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioCalle()
	{
		return $this->domicilio_calle;
	}

	/**
	 * Get the [domicilio_numero] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioNumero()
	{
		return $this->domicilio_numero;
	}

	/**
	 * Get the [domicilio_manzana] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioManzana()
	{
		return $this->domicilio_manzana;
	}

	/**
	 * Get the [domicilio_barrio] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioBarrio()
	{
		return $this->domicilio_barrio;
	}

	/**
	 * Get the [domicilio_piso] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioPiso()
	{
		return $this->domicilio_piso;
	}

	/**
	 * Get the [domicilio_depto] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilioDepto()
	{
		return $this->domicilio_depto;
	}

	/**
	 * Get the [localidad_id] column value.
	 * 
	 * @return     int
	 */
	public function getLocalidadId()
	{
		return $this->localidad_id;
	}

	/**
	 * Get the [provincia_id] column value.
	 * 
	 * @return     int
	 */
	public function getProvinciaId()
	{
		return $this->provincia_id;
	}

	/**
	 * Get the [comentario] column value.
	 * 
	 * @return     string
	 */
	public function getComentario()
	{
		return $this->comentario;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UserProfilePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = UserProfilePeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [language] column.
	 * Lenguaje nativo del usuario
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setLanguage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->language !== $v || $v === 'es') {
			$this->language = $v;
			$this->modifiedColumns[] = UserProfilePeer::LANGUAGE;
		}

		return $this;
	} // setLanguage()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = UserProfilePeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [apellido] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setApellido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->apellido !== $v) {
			$this->apellido = $v;
			$this->modifiedColumns[] = UserProfilePeer::APELLIDO;
		}

		return $this;
	} // setApellido()

	/**
	 * Sets the value of [fdn] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setFdn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fdn !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fdn !== null && $tmpDt = new DateTime($this->fdn)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fdn = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = UserProfilePeer::FDN;
			}
		} // if either are not null

		return $this;
	} // setFdn()

	/**
	 * Set the value of [nacionalidad] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setNacionalidad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nacionalidad !== $v) {
			$this->nacionalidad = $v;
			$this->modifiedColumns[] = UserProfilePeer::NACIONALIDAD;
		}

		if ($this->aPais !== null && $this->aPais->getId() !== $v) {
			$this->aPais = null;
		}

		return $this;
	} // setNacionalidad()

	/**
	 * Set the value of [documento_tipo] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDocumentoTipo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->documento_tipo !== $v) {
			$this->documento_tipo = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOCUMENTO_TIPO;
		}

		return $this;
	} // setDocumentoTipo()

	/**
	 * Set the value of [documento_numero] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDocumentoNumero($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->documento_numero !== $v) {
			$this->documento_numero = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOCUMENTO_NUMERO;
		}

		return $this;
	} // setDocumentoNumero()

	/**
	 * Set the value of [cuil] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setCuil($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cuil !== $v) {
			$this->cuil = $v;
			$this->modifiedColumns[] = UserProfilePeer::CUIL;
		}

		return $this;
	} // setCuil()

	/**
	 * Set the value of [legajo] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setLegajo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->legajo !== $v) {
			$this->legajo = $v;
			$this->modifiedColumns[] = UserProfilePeer::LEGAJO;
		}

		return $this;
	} // setLegajo()

	/**
	 * Set the value of [telefono] column.
	 * Telefono fijo del usuario
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono !== $v) {
			$this->telefono = $v;
			$this->modifiedColumns[] = UserProfilePeer::TELEFONO;
		}

		return $this;
	} // setTelefono()

	/**
	 * Set the value of [movil] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setMovil($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->movil !== $v) {
			$this->movil = $v;
			$this->modifiedColumns[] = UserProfilePeer::MOVIL;
		}

		return $this;
	} // setMovil()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = UserProfilePeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [domicilio_calle] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioCalle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_calle !== $v) {
			$this->domicilio_calle = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_CALLE;
		}

		return $this;
	} // setDomicilioCalle()

	/**
	 * Set the value of [domicilio_numero] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioNumero($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_numero !== $v) {
			$this->domicilio_numero = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_NUMERO;
		}

		return $this;
	} // setDomicilioNumero()

	/**
	 * Set the value of [domicilio_manzana] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioManzana($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_manzana !== $v) {
			$this->domicilio_manzana = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_MANZANA;
		}

		return $this;
	} // setDomicilioManzana()

	/**
	 * Set the value of [domicilio_barrio] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioBarrio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_barrio !== $v) {
			$this->domicilio_barrio = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_BARRIO;
		}

		return $this;
	} // setDomicilioBarrio()

	/**
	 * Set the value of [domicilio_piso] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioPiso($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_piso !== $v) {
			$this->domicilio_piso = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_PISO;
		}

		return $this;
	} // setDomicilioPiso()

	/**
	 * Set the value of [domicilio_depto] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setDomicilioDepto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio_depto !== $v) {
			$this->domicilio_depto = $v;
			$this->modifiedColumns[] = UserProfilePeer::DOMICILIO_DEPTO;
		}

		return $this;
	} // setDomicilioDepto()

	/**
	 * Set the value of [localidad_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setLocalidadId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->localidad_id !== $v) {
			$this->localidad_id = $v;
			$this->modifiedColumns[] = UserProfilePeer::LOCALIDAD_ID;
		}

		if ($this->aLocalidad !== null && $this->aLocalidad->getId() !== $v) {
			$this->aLocalidad = null;
		}

		return $this;
	} // setLocalidadId()

	/**
	 * Set the value of [provincia_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setProvinciaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->provincia_id !== $v) {
			$this->provincia_id = $v;
			$this->modifiedColumns[] = UserProfilePeer::PROVINCIA_ID;
		}

		if ($this->aProvincia !== null && $this->aProvincia->getId() !== $v) {
			$this->aProvincia = null;
		}

		return $this;
	} // setProvinciaId()

	/**
	 * Set the value of [comentario] column.
	 * 
	 * @param      string $v new value
	 * @return     UserProfile The current object (for fluent API support)
	 */
	public function setComentario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comentario !== $v) {
			$this->comentario = $v;
			$this->modifiedColumns[] = UserProfilePeer::COMENTARIO;
		}

		return $this;
	} // setComentario()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UserProfilePeer::LANGUAGE))) {
				return false;
			}

			if ($this->language !== 'es') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->language = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->apellido = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fdn = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->nacionalidad = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->documento_tipo = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->documento_numero = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->cuil = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->legajo = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->telefono = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->movil = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->email = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->domicilio_calle = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->domicilio_numero = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->domicilio_manzana = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->domicilio_barrio = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->domicilio_piso = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->domicilio_depto = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->localidad_id = ($row[$startcol + 20] !== null) ? (int) $row[$startcol + 20] : null;
			$this->provincia_id = ($row[$startcol + 21] !== null) ? (int) $row[$startcol + 21] : null;
			$this->comentario = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 23; // 23 = UserProfilePeer::NUM_COLUMNS - UserProfilePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating UserProfile object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
		if ($this->aPais !== null && $this->nacionalidad !== $this->aPais->getId()) {
			$this->aPais = null;
		}
		if ($this->aLocalidad !== null && $this->localidad_id !== $this->aLocalidad->getId()) {
			$this->aLocalidad = null;
		}
		if ($this->aProvincia !== null && $this->provincia_id !== $this->aProvincia->getId()) {
			$this->aProvincia = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserProfilePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUser = null;
			$this->aPais = null;
			$this->aLocalidad = null;
			$this->aProvincia = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserProfile:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserProfilePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUserProfile:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserProfile:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUserProfile:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserProfilePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->aPais !== null) {
				if ($this->aPais->isModified() || $this->aPais->isNew()) {
					$affectedRows += $this->aPais->save($con);
				}
				$this->setPais($this->aPais);
			}

			if ($this->aLocalidad !== null) {
				if ($this->aLocalidad->isModified() || $this->aLocalidad->isNew()) {
					$affectedRows += $this->aLocalidad->save($con);
				}
				$this->setLocalidad($this->aLocalidad);
			}

			if ($this->aProvincia !== null) {
				if ($this->aProvincia->isModified() || $this->aProvincia->isNew()) {
					$affectedRows += $this->aProvincia->save($con);
				}
				$this->setProvincia($this->aProvincia);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserProfilePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserProfilePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserProfilePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}

			if ($this->aPais !== null) {
				if (!$this->aPais->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPais->getValidationFailures());
				}
			}

			if ($this->aLocalidad !== null) {
				if (!$this->aLocalidad->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLocalidad->getValidationFailures());
				}
			}

			if ($this->aProvincia !== null) {
				if (!$this->aProvincia->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProvincia->getValidationFailures());
				}
			}


			if (($retval = UserProfilePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserProfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserId();
				break;
			case 2:
				return $this->getLanguage();
				break;
			case 3:
				return $this->getNombre();
				break;
			case 4:
				return $this->getApellido();
				break;
			case 5:
				return $this->getFdn();
				break;
			case 6:
				return $this->getNacionalidad();
				break;
			case 7:
				return $this->getDocumentoTipo();
				break;
			case 8:
				return $this->getDocumentoNumero();
				break;
			case 9:
				return $this->getCuil();
				break;
			case 10:
				return $this->getLegajo();
				break;
			case 11:
				return $this->getTelefono();
				break;
			case 12:
				return $this->getMovil();
				break;
			case 13:
				return $this->getEmail();
				break;
			case 14:
				return $this->getDomicilioCalle();
				break;
			case 15:
				return $this->getDomicilioNumero();
				break;
			case 16:
				return $this->getDomicilioManzana();
				break;
			case 17:
				return $this->getDomicilioBarrio();
				break;
			case 18:
				return $this->getDomicilioPiso();
				break;
			case 19:
				return $this->getDomicilioDepto();
				break;
			case 20:
				return $this->getLocalidadId();
				break;
			case 21:
				return $this->getProvinciaId();
				break;
			case 22:
				return $this->getComentario();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserProfilePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserId(),
			$keys[2] => $this->getLanguage(),
			$keys[3] => $this->getNombre(),
			$keys[4] => $this->getApellido(),
			$keys[5] => $this->getFdn(),
			$keys[6] => $this->getNacionalidad(),
			$keys[7] => $this->getDocumentoTipo(),
			$keys[8] => $this->getDocumentoNumero(),
			$keys[9] => $this->getCuil(),
			$keys[10] => $this->getLegajo(),
			$keys[11] => $this->getTelefono(),
			$keys[12] => $this->getMovil(),
			$keys[13] => $this->getEmail(),
			$keys[14] => $this->getDomicilioCalle(),
			$keys[15] => $this->getDomicilioNumero(),
			$keys[16] => $this->getDomicilioManzana(),
			$keys[17] => $this->getDomicilioBarrio(),
			$keys[18] => $this->getDomicilioPiso(),
			$keys[19] => $this->getDomicilioDepto(),
			$keys[20] => $this->getLocalidadId(),
			$keys[21] => $this->getProvinciaId(),
			$keys[22] => $this->getComentario(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserProfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserId($value);
				break;
			case 2:
				$this->setLanguage($value);
				break;
			case 3:
				$this->setNombre($value);
				break;
			case 4:
				$this->setApellido($value);
				break;
			case 5:
				$this->setFdn($value);
				break;
			case 6:
				$this->setNacionalidad($value);
				break;
			case 7:
				$this->setDocumentoTipo($value);
				break;
			case 8:
				$this->setDocumentoNumero($value);
				break;
			case 9:
				$this->setCuil($value);
				break;
			case 10:
				$this->setLegajo($value);
				break;
			case 11:
				$this->setTelefono($value);
				break;
			case 12:
				$this->setMovil($value);
				break;
			case 13:
				$this->setEmail($value);
				break;
			case 14:
				$this->setDomicilioCalle($value);
				break;
			case 15:
				$this->setDomicilioNumero($value);
				break;
			case 16:
				$this->setDomicilioManzana($value);
				break;
			case 17:
				$this->setDomicilioBarrio($value);
				break;
			case 18:
				$this->setDomicilioPiso($value);
				break;
			case 19:
				$this->setDomicilioDepto($value);
				break;
			case 20:
				$this->setLocalidadId($value);
				break;
			case 21:
				$this->setProvinciaId($value);
				break;
			case 22:
				$this->setComentario($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserProfilePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setLanguage($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setApellido($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFdn($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNacionalidad($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDocumentoTipo($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDocumentoNumero($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCuil($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setLegajo($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTelefono($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setMovil($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setEmail($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setDomicilioCalle($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDomicilioNumero($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setDomicilioManzana($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setDomicilioBarrio($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setDomicilioPiso($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setDomicilioDepto($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setLocalidadId($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setProvinciaId($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setComentario($arr[$keys[22]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserProfilePeer::DATABASE_NAME);

		if ($this->isColumnModified(UserProfilePeer::ID)) $criteria->add(UserProfilePeer::ID, $this->id);
		if ($this->isColumnModified(UserProfilePeer::USER_ID)) $criteria->add(UserProfilePeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(UserProfilePeer::LANGUAGE)) $criteria->add(UserProfilePeer::LANGUAGE, $this->language);
		if ($this->isColumnModified(UserProfilePeer::NOMBRE)) $criteria->add(UserProfilePeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(UserProfilePeer::APELLIDO)) $criteria->add(UserProfilePeer::APELLIDO, $this->apellido);
		if ($this->isColumnModified(UserProfilePeer::FDN)) $criteria->add(UserProfilePeer::FDN, $this->fdn);
		if ($this->isColumnModified(UserProfilePeer::NACIONALIDAD)) $criteria->add(UserProfilePeer::NACIONALIDAD, $this->nacionalidad);
		if ($this->isColumnModified(UserProfilePeer::DOCUMENTO_TIPO)) $criteria->add(UserProfilePeer::DOCUMENTO_TIPO, $this->documento_tipo);
		if ($this->isColumnModified(UserProfilePeer::DOCUMENTO_NUMERO)) $criteria->add(UserProfilePeer::DOCUMENTO_NUMERO, $this->documento_numero);
		if ($this->isColumnModified(UserProfilePeer::CUIL)) $criteria->add(UserProfilePeer::CUIL, $this->cuil);
		if ($this->isColumnModified(UserProfilePeer::LEGAJO)) $criteria->add(UserProfilePeer::LEGAJO, $this->legajo);
		if ($this->isColumnModified(UserProfilePeer::TELEFONO)) $criteria->add(UserProfilePeer::TELEFONO, $this->telefono);
		if ($this->isColumnModified(UserProfilePeer::MOVIL)) $criteria->add(UserProfilePeer::MOVIL, $this->movil);
		if ($this->isColumnModified(UserProfilePeer::EMAIL)) $criteria->add(UserProfilePeer::EMAIL, $this->email);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_CALLE)) $criteria->add(UserProfilePeer::DOMICILIO_CALLE, $this->domicilio_calle);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_NUMERO)) $criteria->add(UserProfilePeer::DOMICILIO_NUMERO, $this->domicilio_numero);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_MANZANA)) $criteria->add(UserProfilePeer::DOMICILIO_MANZANA, $this->domicilio_manzana);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_BARRIO)) $criteria->add(UserProfilePeer::DOMICILIO_BARRIO, $this->domicilio_barrio);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_PISO)) $criteria->add(UserProfilePeer::DOMICILIO_PISO, $this->domicilio_piso);
		if ($this->isColumnModified(UserProfilePeer::DOMICILIO_DEPTO)) $criteria->add(UserProfilePeer::DOMICILIO_DEPTO, $this->domicilio_depto);
		if ($this->isColumnModified(UserProfilePeer::LOCALIDAD_ID)) $criteria->add(UserProfilePeer::LOCALIDAD_ID, $this->localidad_id);
		if ($this->isColumnModified(UserProfilePeer::PROVINCIA_ID)) $criteria->add(UserProfilePeer::PROVINCIA_ID, $this->provincia_id);
		if ($this->isColumnModified(UserProfilePeer::COMENTARIO)) $criteria->add(UserProfilePeer::COMENTARIO, $this->comentario);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserProfilePeer::DATABASE_NAME);

		$criteria->add(UserProfilePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of UserProfile (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setLanguage($this->language);

		$copyObj->setNombre($this->nombre);

		$copyObj->setApellido($this->apellido);

		$copyObj->setFdn($this->fdn);

		$copyObj->setNacionalidad($this->nacionalidad);

		$copyObj->setDocumentoTipo($this->documento_tipo);

		$copyObj->setDocumentoNumero($this->documento_numero);

		$copyObj->setCuil($this->cuil);

		$copyObj->setLegajo($this->legajo);

		$copyObj->setTelefono($this->telefono);

		$copyObj->setMovil($this->movil);

		$copyObj->setEmail($this->email);

		$copyObj->setDomicilioCalle($this->domicilio_calle);

		$copyObj->setDomicilioNumero($this->domicilio_numero);

		$copyObj->setDomicilioManzana($this->domicilio_manzana);

		$copyObj->setDomicilioBarrio($this->domicilio_barrio);

		$copyObj->setDomicilioPiso($this->domicilio_piso);

		$copyObj->setDomicilioDepto($this->domicilio_depto);

		$copyObj->setLocalidadId($this->localidad_id);

		$copyObj->setProvinciaId($this->provincia_id);

		$copyObj->setComentario($this->comentario);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     UserProfile Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserProfilePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserProfilePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     UserProfile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addUserProfile($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$c = new Criteria(sfGuardUserPeer::DATABASE_NAME);
			$c->add(sfGuardUserPeer::ID, $this->user_id);
			$this->asfGuardUser = sfGuardUserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addUserProfiles($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Declares an association between this object and a Pais object.
	 *
	 * @param      Pais $v
	 * @return     UserProfile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPais(Pais $v = null)
	{
		if ($v === null) {
			$this->setNacionalidad(NULL);
		} else {
			$this->setNacionalidad($v->getId());
		}

		$this->aPais = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Pais object, it will not be re-added.
		if ($v !== null) {
			$v->addUserProfile($this);
		}

		return $this;
	}


	/**
	 * Get the associated Pais object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Pais The associated Pais object.
	 * @throws     PropelException
	 */
	public function getPais(PropelPDO $con = null)
	{
		if ($this->aPais === null && ($this->nacionalidad !== null)) {
			$c = new Criteria(PaisPeer::DATABASE_NAME);
			$c->add(PaisPeer::ID, $this->nacionalidad);
			$this->aPais = PaisPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPais->addUserProfiles($this);
			 */
		}
		return $this->aPais;
	}

	/**
	 * Declares an association between this object and a Localidad object.
	 *
	 * @param      Localidad $v
	 * @return     UserProfile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLocalidad(Localidad $v = null)
	{
		if ($v === null) {
			$this->setLocalidadId(NULL);
		} else {
			$this->setLocalidadId($v->getId());
		}

		$this->aLocalidad = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Localidad object, it will not be re-added.
		if ($v !== null) {
			$v->addUserProfile($this);
		}

		return $this;
	}


	/**
	 * Get the associated Localidad object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Localidad The associated Localidad object.
	 * @throws     PropelException
	 */
	public function getLocalidad(PropelPDO $con = null)
	{
		if ($this->aLocalidad === null && ($this->localidad_id !== null)) {
			$c = new Criteria(LocalidadPeer::DATABASE_NAME);
			$c->add(LocalidadPeer::ID, $this->localidad_id);
			$this->aLocalidad = LocalidadPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLocalidad->addUserProfiles($this);
			 */
		}
		return $this->aLocalidad;
	}

	/**
	 * Declares an association between this object and a Provincia object.
	 *
	 * @param      Provincia $v
	 * @return     UserProfile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProvincia(Provincia $v = null)
	{
		if ($v === null) {
			$this->setProvinciaId(NULL);
		} else {
			$this->setProvinciaId($v->getId());
		}

		$this->aProvincia = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Provincia object, it will not be re-added.
		if ($v !== null) {
			$v->addUserProfile($this);
		}

		return $this;
	}


	/**
	 * Get the associated Provincia object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Provincia The associated Provincia object.
	 * @throws     PropelException
	 */
	public function getProvincia(PropelPDO $con = null)
	{
		if ($this->aProvincia === null && ($this->provincia_id !== null)) {
			$c = new Criteria(ProvinciaPeer::DATABASE_NAME);
			$c->add(ProvinciaPeer::ID, $this->provincia_id);
			$this->aProvincia = ProvinciaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProvincia->addUserProfiles($this);
			 */
		}
		return $this->aProvincia;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->asfGuardUser = null;
			$this->aPais = null;
			$this->aLocalidad = null;
			$this->aProvincia = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUserProfile:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUserProfile::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUserProfile
