<?php

/**
 * Base class that represents a row from the 'compra' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jan 12 14:28:40 2010
 *
 * @package    lib.model.om
 */
abstract class BaseCompra extends BaseObject  implements Persistent {


  const PEER = 'CompraPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CompraPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the producto_id field.
	 * @var        int
	 */
	protected $producto_id;

	/**
	 * The value for the cantidad field.
	 * @var        int
	 */
	protected $cantidad;

	/**
	 * The value for the proveedor_id field.
	 * @var        int
	 */
	protected $proveedor_id;

	/**
	 * The value for the nota_pedido_id field.
	 * @var        int
	 */
	protected $nota_pedido_id;

	/**
	 * The value for the precio field.
	 * @var        double
	 */
	protected $precio;

	/**
	 * The value for the moneda field.
	 * @var        string
	 */
	protected $moneda;

	/**
	 * The value for the fecha field.
	 * @var        string
	 */
	protected $fecha;

	/**
	 * The value for the fecha_entrega field.
	 * @var        string
	 */
	protected $fecha_entrega;

	/**
	 * The value for the comentario field.
	 * @var        string
	 */
	protected $comentario;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Producto
	 */
	protected $aProducto;

	/**
	 * @var        Proveedor
	 */
	protected $aProveedor;

	/**
	 * @var        NotaPedido
	 */
	protected $aNotaPedido;

	/**
	 * @var        array CompraEstado[] Collection to store aggregation of CompraEstado objects.
	 */
	protected $collCompraEstados;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCompraEstados.
	 */
	private $lastCompraEstadoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCompra object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [producto_id] column value.
	 * 
	 * @return     int
	 */
	public function getProductoId()
	{
		return $this->producto_id;
	}

	/**
	 * Get the [cantidad] column value.
	 * 
	 * @return     int
	 */
	public function getCantidad()
	{
		return $this->cantidad;
	}

	/**
	 * Get the [proveedor_id] column value.
	 * 
	 * @return     int
	 */
	public function getProveedorId()
	{
		return $this->proveedor_id;
	}

	/**
	 * Get the [nota_pedido_id] column value.
	 * 
	 * @return     int
	 */
	public function getNotaPedidoId()
	{
		return $this->nota_pedido_id;
	}

	/**
	 * Get the [precio] column value.
	 * 
	 * @return     double
	 */
	public function getPrecio()
	{
		return $this->precio;
	}

	/**
	 * Get the [moneda] column value.
	 * 
	 * @return     string
	 */
	public function getMoneda()
	{
		return $this->moneda;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFecha($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha === null) {
			return null;
		}


		if ($this->fecha === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_entrega] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaEntrega($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_entrega === null) {
			return null;
		}


		if ($this->fecha_entrega === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_entrega);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_entrega, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [comentario] column value.
	 * 
	 * @return     string
	 */
	public function getComentario()
	{
		return $this->comentario;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CompraPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [producto_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setProductoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->producto_id !== $v) {
			$this->producto_id = $v;
			$this->modifiedColumns[] = CompraPeer::PRODUCTO_ID;
		}

		if ($this->aProducto !== null && $this->aProducto->getId() !== $v) {
			$this->aProducto = null;
		}

		return $this;
	} // setProductoId()

	/**
	 * Set the value of [cantidad] column.
	 * 
	 * @param      int $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setCantidad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cantidad !== $v) {
			$this->cantidad = $v;
			$this->modifiedColumns[] = CompraPeer::CANTIDAD;
		}

		return $this;
	} // setCantidad()

	/**
	 * Set the value of [proveedor_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setProveedorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->proveedor_id !== $v) {
			$this->proveedor_id = $v;
			$this->modifiedColumns[] = CompraPeer::PROVEEDOR_ID;
		}

		if ($this->aProveedor !== null && $this->aProveedor->getId() !== $v) {
			$this->aProveedor = null;
		}

		return $this;
	} // setProveedorId()

	/**
	 * Set the value of [nota_pedido_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setNotaPedidoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nota_pedido_id !== $v) {
			$this->nota_pedido_id = $v;
			$this->modifiedColumns[] = CompraPeer::NOTA_PEDIDO_ID;
		}

		if ($this->aNotaPedido !== null && $this->aNotaPedido->getId() !== $v) {
			$this->aNotaPedido = null;
		}

		return $this;
	} // setNotaPedidoId()

	/**
	 * Set the value of [precio] column.
	 * 
	 * @param      double $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setPrecio($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->precio !== $v) {
			$this->precio = $v;
			$this->modifiedColumns[] = CompraPeer::PRECIO;
		}

		return $this;
	} // setPrecio()

	/**
	 * Set the value of [moneda] column.
	 * 
	 * @param      string $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setMoneda($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->moneda !== $v) {
			$this->moneda = $v;
			$this->modifiedColumns[] = CompraPeer::MONEDA;
		}

		return $this;
	} // setMoneda()

	/**
	 * Sets the value of [fecha] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setFecha($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha !== null && $tmpDt = new DateTime($this->fecha)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CompraPeer::FECHA;
			}
		} // if either are not null

		return $this;
	} // setFecha()

	/**
	 * Sets the value of [fecha_entrega] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setFechaEntrega($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_entrega !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_entrega !== null && $tmpDt = new DateTime($this->fecha_entrega)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_entrega = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CompraPeer::FECHA_ENTREGA;
			}
		} // if either are not null

		return $this;
	} // setFechaEntrega()

	/**
	 * Set the value of [comentario] column.
	 * 
	 * @param      string $v new value
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setComentario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comentario !== $v) {
			$this->comentario = $v;
			$this->modifiedColumns[] = CompraPeer::COMENTARIO;
		}

		return $this;
	} // setComentario()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Compra The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CompraPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->producto_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->cantidad = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->proveedor_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->nota_pedido_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->precio = ($row[$startcol + 5] !== null) ? (double) $row[$startcol + 5] : null;
			$this->moneda = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fecha = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fecha_entrega = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->comentario = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->created_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = CompraPeer::NUM_COLUMNS - CompraPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Compra object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aProducto !== null && $this->producto_id !== $this->aProducto->getId()) {
			$this->aProducto = null;
		}
		if ($this->aProveedor !== null && $this->proveedor_id !== $this->aProveedor->getId()) {
			$this->aProveedor = null;
		}
		if ($this->aNotaPedido !== null && $this->nota_pedido_id !== $this->aNotaPedido->getId()) {
			$this->aNotaPedido = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CompraPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aProducto = null;
			$this->aProveedor = null;
			$this->aNotaPedido = null;
			$this->collCompraEstados = null;
			$this->lastCompraEstadoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompra:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CompraPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCompra:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompra:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(CompraPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCompra:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CompraPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProducto !== null) {
				if ($this->aProducto->isModified() || $this->aProducto->isNew()) {
					$affectedRows += $this->aProducto->save($con);
				}
				$this->setProducto($this->aProducto);
			}

			if ($this->aProveedor !== null) {
				if ($this->aProveedor->isModified() || $this->aProveedor->isNew()) {
					$affectedRows += $this->aProveedor->save($con);
				}
				$this->setProveedor($this->aProveedor);
			}

			if ($this->aNotaPedido !== null) {
				if ($this->aNotaPedido->isModified() || $this->aNotaPedido->isNew()) {
					$affectedRows += $this->aNotaPedido->save($con);
				}
				$this->setNotaPedido($this->aNotaPedido);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CompraPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CompraPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CompraPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCompraEstados !== null) {
				foreach ($this->collCompraEstados as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProducto !== null) {
				if (!$this->aProducto->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProducto->getValidationFailures());
				}
			}

			if ($this->aProveedor !== null) {
				if (!$this->aProveedor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProveedor->getValidationFailures());
				}
			}

			if ($this->aNotaPedido !== null) {
				if (!$this->aNotaPedido->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aNotaPedido->getValidationFailures());
				}
			}


			if (($retval = CompraPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCompraEstados !== null) {
					foreach ($this->collCompraEstados as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CompraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getProductoId();
				break;
			case 2:
				return $this->getCantidad();
				break;
			case 3:
				return $this->getProveedorId();
				break;
			case 4:
				return $this->getNotaPedidoId();
				break;
			case 5:
				return $this->getPrecio();
				break;
			case 6:
				return $this->getMoneda();
				break;
			case 7:
				return $this->getFecha();
				break;
			case 8:
				return $this->getFechaEntrega();
				break;
			case 9:
				return $this->getComentario();
				break;
			case 10:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CompraPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getProductoId(),
			$keys[2] => $this->getCantidad(),
			$keys[3] => $this->getProveedorId(),
			$keys[4] => $this->getNotaPedidoId(),
			$keys[5] => $this->getPrecio(),
			$keys[6] => $this->getMoneda(),
			$keys[7] => $this->getFecha(),
			$keys[8] => $this->getFechaEntrega(),
			$keys[9] => $this->getComentario(),
			$keys[10] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CompraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setProductoId($value);
				break;
			case 2:
				$this->setCantidad($value);
				break;
			case 3:
				$this->setProveedorId($value);
				break;
			case 4:
				$this->setNotaPedidoId($value);
				break;
			case 5:
				$this->setPrecio($value);
				break;
			case 6:
				$this->setMoneda($value);
				break;
			case 7:
				$this->setFecha($value);
				break;
			case 8:
				$this->setFechaEntrega($value);
				break;
			case 9:
				$this->setComentario($value);
				break;
			case 10:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CompraPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setProductoId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCantidad($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setProveedorId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNotaPedidoId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPrecio($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMoneda($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFecha($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFechaEntrega($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setComentario($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedAt($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CompraPeer::DATABASE_NAME);

		if ($this->isColumnModified(CompraPeer::ID)) $criteria->add(CompraPeer::ID, $this->id);
		if ($this->isColumnModified(CompraPeer::PRODUCTO_ID)) $criteria->add(CompraPeer::PRODUCTO_ID, $this->producto_id);
		if ($this->isColumnModified(CompraPeer::CANTIDAD)) $criteria->add(CompraPeer::CANTIDAD, $this->cantidad);
		if ($this->isColumnModified(CompraPeer::PROVEEDOR_ID)) $criteria->add(CompraPeer::PROVEEDOR_ID, $this->proveedor_id);
		if ($this->isColumnModified(CompraPeer::NOTA_PEDIDO_ID)) $criteria->add(CompraPeer::NOTA_PEDIDO_ID, $this->nota_pedido_id);
		if ($this->isColumnModified(CompraPeer::PRECIO)) $criteria->add(CompraPeer::PRECIO, $this->precio);
		if ($this->isColumnModified(CompraPeer::MONEDA)) $criteria->add(CompraPeer::MONEDA, $this->moneda);
		if ($this->isColumnModified(CompraPeer::FECHA)) $criteria->add(CompraPeer::FECHA, $this->fecha);
		if ($this->isColumnModified(CompraPeer::FECHA_ENTREGA)) $criteria->add(CompraPeer::FECHA_ENTREGA, $this->fecha_entrega);
		if ($this->isColumnModified(CompraPeer::COMENTARIO)) $criteria->add(CompraPeer::COMENTARIO, $this->comentario);
		if ($this->isColumnModified(CompraPeer::CREATED_AT)) $criteria->add(CompraPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CompraPeer::DATABASE_NAME);

		$criteria->add(CompraPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Compra (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setProductoId($this->producto_id);

		$copyObj->setCantidad($this->cantidad);

		$copyObj->setProveedorId($this->proveedor_id);

		$copyObj->setNotaPedidoId($this->nota_pedido_id);

		$copyObj->setPrecio($this->precio);

		$copyObj->setMoneda($this->moneda);

		$copyObj->setFecha($this->fecha);

		$copyObj->setFechaEntrega($this->fecha_entrega);

		$copyObj->setComentario($this->comentario);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCompraEstados() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCompraEstado($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Compra Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CompraPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CompraPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Producto object.
	 *
	 * @param      Producto $v
	 * @return     Compra The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProducto(Producto $v = null)
	{
		if ($v === null) {
			$this->setProductoId(NULL);
		} else {
			$this->setProductoId($v->getId());
		}

		$this->aProducto = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Producto object, it will not be re-added.
		if ($v !== null) {
			$v->addCompra($this);
		}

		return $this;
	}


	/**
	 * Get the associated Producto object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Producto The associated Producto object.
	 * @throws     PropelException
	 */
	public function getProducto(PropelPDO $con = null)
	{
		if ($this->aProducto === null && ($this->producto_id !== null)) {
			$c = new Criteria(ProductoPeer::DATABASE_NAME);
			$c->add(ProductoPeer::ID, $this->producto_id);
			$this->aProducto = ProductoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProducto->addCompras($this);
			 */
		}
		return $this->aProducto;
	}

	/**
	 * Declares an association between this object and a Proveedor object.
	 *
	 * @param      Proveedor $v
	 * @return     Compra The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProveedor(Proveedor $v = null)
	{
		if ($v === null) {
			$this->setProveedorId(NULL);
		} else {
			$this->setProveedorId($v->getId());
		}

		$this->aProveedor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Proveedor object, it will not be re-added.
		if ($v !== null) {
			$v->addCompra($this);
		}

		return $this;
	}


	/**
	 * Get the associated Proveedor object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Proveedor The associated Proveedor object.
	 * @throws     PropelException
	 */
	public function getProveedor(PropelPDO $con = null)
	{
		if ($this->aProveedor === null && ($this->proveedor_id !== null)) {
			$c = new Criteria(ProveedorPeer::DATABASE_NAME);
			$c->add(ProveedorPeer::ID, $this->proveedor_id);
			$this->aProveedor = ProveedorPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProveedor->addCompras($this);
			 */
		}
		return $this->aProveedor;
	}

	/**
	 * Declares an association between this object and a NotaPedido object.
	 *
	 * @param      NotaPedido $v
	 * @return     Compra The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setNotaPedido(NotaPedido $v = null)
	{
		if ($v === null) {
			$this->setNotaPedidoId(NULL);
		} else {
			$this->setNotaPedidoId($v->getId());
		}

		$this->aNotaPedido = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the NotaPedido object, it will not be re-added.
		if ($v !== null) {
			$v->addCompra($this);
		}

		return $this;
	}


	/**
	 * Get the associated NotaPedido object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     NotaPedido The associated NotaPedido object.
	 * @throws     PropelException
	 */
	public function getNotaPedido(PropelPDO $con = null)
	{
		if ($this->aNotaPedido === null && ($this->nota_pedido_id !== null)) {
			$c = new Criteria(NotaPedidoPeer::DATABASE_NAME);
			$c->add(NotaPedidoPeer::ID, $this->nota_pedido_id);
			$this->aNotaPedido = NotaPedidoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aNotaPedido->addCompras($this);
			 */
		}
		return $this->aNotaPedido;
	}

	/**
	 * Clears out the collCompraEstados collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCompraEstados()
	 */
	public function clearCompraEstados()
	{
		$this->collCompraEstados = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCompraEstados collection (array).
	 *
	 * By default this just sets the collCompraEstados collection to an empty array (like clearcollCompraEstados());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCompraEstados()
	{
		$this->collCompraEstados = array();
	}

	/**
	 * Gets an array of CompraEstado objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Compra has previously been saved, it will retrieve
	 * related CompraEstados from storage. If this Compra is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CompraEstado[]
	 * @throws     PropelException
	 */
	public function getCompraEstados($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CompraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompraEstados === null) {
			if ($this->isNew()) {
			   $this->collCompraEstados = array();
			} else {

				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				CompraEstadoPeer::addSelectColumns($criteria);
				$this->collCompraEstados = CompraEstadoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				CompraEstadoPeer::addSelectColumns($criteria);
				if (!isset($this->lastCompraEstadoCriteria) || !$this->lastCompraEstadoCriteria->equals($criteria)) {
					$this->collCompraEstados = CompraEstadoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCompraEstadoCriteria = $criteria;
		return $this->collCompraEstados;
	}

	/**
	 * Returns the number of related CompraEstado objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CompraEstado objects.
	 * @throws     PropelException
	 */
	public function countCompraEstados(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CompraPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCompraEstados === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				$count = CompraEstadoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				if (!isset($this->lastCompraEstadoCriteria) || !$this->lastCompraEstadoCriteria->equals($criteria)) {
					$count = CompraEstadoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCompraEstados);
				}
			} else {
				$count = count($this->collCompraEstados);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CompraEstado object to this object
	 * through the CompraEstado foreign key attribute.
	 *
	 * @param      CompraEstado $l CompraEstado
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCompraEstado(CompraEstado $l)
	{
		if ($this->collCompraEstados === null) {
			$this->initCompraEstados();
		}
		if (!in_array($l, $this->collCompraEstados, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCompraEstados, $l);
			$l->setCompra($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compra is new, it will return
	 * an empty collection; or if this Compra has previously
	 * been saved, it will retrieve related CompraEstados from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compra.
	 */
	public function getCompraEstadosJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CompraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompraEstados === null) {
			if ($this->isNew()) {
				$this->collCompraEstados = array();
			} else {

				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

			if (!isset($this->lastCompraEstadoCriteria) || !$this->lastCompraEstadoCriteria->equals($criteria)) {
				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompraEstadoCriteria = $criteria;

		return $this->collCompraEstados;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compra is new, it will return
	 * an empty collection; or if this Compra has previously
	 * been saved, it will retrieve related CompraEstados from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compra.
	 */
	public function getCompraEstadosJoinEstado($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CompraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompraEstados === null) {
			if ($this->isNew()) {
				$this->collCompraEstados = array();
			} else {

				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinEstado($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

			if (!isset($this->lastCompraEstadoCriteria) || !$this->lastCompraEstadoCriteria->equals($criteria)) {
				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinEstado($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompraEstadoCriteria = $criteria;

		return $this->collCompraEstados;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Compra is new, it will return
	 * an empty collection; or if this Compra has previously
	 * been saved, it will retrieve related CompraEstados from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Compra.
	 */
	public function getCompraEstadosJoinRecepcionPedido($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CompraPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompraEstados === null) {
			if ($this->isNew()) {
				$this->collCompraEstados = array();
			} else {

				$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinRecepcionPedido($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompraEstadoPeer::COMPRA_ID, $this->id);

			if (!isset($this->lastCompraEstadoCriteria) || !$this->lastCompraEstadoCriteria->equals($criteria)) {
				$this->collCompraEstados = CompraEstadoPeer::doSelectJoinRecepcionPedido($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompraEstadoCriteria = $criteria;

		return $this->collCompraEstados;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCompraEstados) {
				foreach ((array) $this->collCompraEstados as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCompraEstados = null;
			$this->aProducto = null;
			$this->aProveedor = null;
			$this->aNotaPedido = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCompra:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCompra::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCompra
