<?php

/**
 * Base static class for performing query and update operations on the 'proveedor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jan 12 14:28:40 2010
 *
 * @package    lib.model.om
 */
abstract class BaseProveedorPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'proveedor';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Proveedor';

	/** The total number of columns. */
	const NUM_COLUMNS = 18;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'proveedor.ID';

	/** the column name for the NOMBRE field */
	const NOMBRE = 'proveedor.NOMBRE';

	/** the column name for the CUIT field */
	const CUIT = 'proveedor.CUIT';

	/** the column name for the RUBRO_ID field */
	const RUBRO_ID = 'proveedor.RUBRO_ID';

	/** the column name for the TELEFONO field */
	const TELEFONO = 'proveedor.TELEFONO';

	/** the column name for the FAX field */
	const FAX = 'proveedor.FAX';

	/** the column name for the MOVIL field */
	const MOVIL = 'proveedor.MOVIL';

	/** the column name for the EMAIL field */
	const EMAIL = 'proveedor.EMAIL';

	/** the column name for the PERSONA_NOMBRE field */
	const PERSONA_NOMBRE = 'proveedor.PERSONA_NOMBRE';

	/** the column name for the PERSONA_APELLIDO field */
	const PERSONA_APELLIDO = 'proveedor.PERSONA_APELLIDO';

	/** the column name for the DIRECCION_CALLE field */
	const DIRECCION_CALLE = 'proveedor.DIRECCION_CALLE';

	/** the column name for the DIRECCION_NUMERO field */
	const DIRECCION_NUMERO = 'proveedor.DIRECCION_NUMERO';

	/** the column name for the DIRECCION_MANZANA field */
	const DIRECCION_MANZANA = 'proveedor.DIRECCION_MANZANA';

	/** the column name for the DIRECCION_BARRIO field */
	const DIRECCION_BARRIO = 'proveedor.DIRECCION_BARRIO';

	/** the column name for the DIRECCION_PISO field */
	const DIRECCION_PISO = 'proveedor.DIRECCION_PISO';

	/** the column name for the DIRECCION_DEPTO field */
	const DIRECCION_DEPTO = 'proveedor.DIRECCION_DEPTO';

	/** the column name for the LOCALIDAD_ID field */
	const LOCALIDAD_ID = 'proveedor.LOCALIDAD_ID';

	/** the column name for the PROVINCIA_ID field */
	const PROVINCIA_ID = 'proveedor.PROVINCIA_ID';

	/**
	 * An identiy map to hold any loaded instances of Proveedor objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Proveedor[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Nombre', 'Cuit', 'RubroId', 'Telefono', 'Fax', 'Movil', 'Email', 'PersonaNombre', 'PersonaApellido', 'DireccionCalle', 'DireccionNumero', 'DireccionManzana', 'DireccionBarrio', 'DireccionPiso', 'DireccionDepto', 'LocalidadId', 'ProvinciaId', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'nombre', 'cuit', 'rubroId', 'telefono', 'fax', 'movil', 'email', 'personaNombre', 'personaApellido', 'direccionCalle', 'direccionNumero', 'direccionManzana', 'direccionBarrio', 'direccionPiso', 'direccionDepto', 'localidadId', 'provinciaId', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NOMBRE, self::CUIT, self::RUBRO_ID, self::TELEFONO, self::FAX, self::MOVIL, self::EMAIL, self::PERSONA_NOMBRE, self::PERSONA_APELLIDO, self::DIRECCION_CALLE, self::DIRECCION_NUMERO, self::DIRECCION_MANZANA, self::DIRECCION_BARRIO, self::DIRECCION_PISO, self::DIRECCION_DEPTO, self::LOCALIDAD_ID, self::PROVINCIA_ID, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'nombre', 'cuit', 'rubro_id', 'telefono', 'fax', 'movil', 'email', 'persona_nombre', 'persona_apellido', 'direccion_calle', 'direccion_numero', 'direccion_manzana', 'direccion_barrio', 'direccion_piso', 'direccion_depto', 'localidad_id', 'provincia_id', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Nombre' => 1, 'Cuit' => 2, 'RubroId' => 3, 'Telefono' => 4, 'Fax' => 5, 'Movil' => 6, 'Email' => 7, 'PersonaNombre' => 8, 'PersonaApellido' => 9, 'DireccionCalle' => 10, 'DireccionNumero' => 11, 'DireccionManzana' => 12, 'DireccionBarrio' => 13, 'DireccionPiso' => 14, 'DireccionDepto' => 15, 'LocalidadId' => 16, 'ProvinciaId' => 17, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'nombre' => 1, 'cuit' => 2, 'rubroId' => 3, 'telefono' => 4, 'fax' => 5, 'movil' => 6, 'email' => 7, 'personaNombre' => 8, 'personaApellido' => 9, 'direccionCalle' => 10, 'direccionNumero' => 11, 'direccionManzana' => 12, 'direccionBarrio' => 13, 'direccionPiso' => 14, 'direccionDepto' => 15, 'localidadId' => 16, 'provinciaId' => 17, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NOMBRE => 1, self::CUIT => 2, self::RUBRO_ID => 3, self::TELEFONO => 4, self::FAX => 5, self::MOVIL => 6, self::EMAIL => 7, self::PERSONA_NOMBRE => 8, self::PERSONA_APELLIDO => 9, self::DIRECCION_CALLE => 10, self::DIRECCION_NUMERO => 11, self::DIRECCION_MANZANA => 12, self::DIRECCION_BARRIO => 13, self::DIRECCION_PISO => 14, self::DIRECCION_DEPTO => 15, self::LOCALIDAD_ID => 16, self::PROVINCIA_ID => 17, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'nombre' => 1, 'cuit' => 2, 'rubro_id' => 3, 'telefono' => 4, 'fax' => 5, 'movil' => 6, 'email' => 7, 'persona_nombre' => 8, 'persona_apellido' => 9, 'direccion_calle' => 10, 'direccion_numero' => 11, 'direccion_manzana' => 12, 'direccion_barrio' => 13, 'direccion_piso' => 14, 'direccion_depto' => 15, 'localidad_id' => 16, 'provincia_id' => 17, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new ProveedorMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ProveedorPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ProveedorPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(ProveedorPeer::ID);

		$criteria->addSelectColumn(ProveedorPeer::NOMBRE);

		$criteria->addSelectColumn(ProveedorPeer::CUIT);

		$criteria->addSelectColumn(ProveedorPeer::RUBRO_ID);

		$criteria->addSelectColumn(ProveedorPeer::TELEFONO);

		$criteria->addSelectColumn(ProveedorPeer::FAX);

		$criteria->addSelectColumn(ProveedorPeer::MOVIL);

		$criteria->addSelectColumn(ProveedorPeer::EMAIL);

		$criteria->addSelectColumn(ProveedorPeer::PERSONA_NOMBRE);

		$criteria->addSelectColumn(ProveedorPeer::PERSONA_APELLIDO);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_CALLE);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_NUMERO);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_MANZANA);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_BARRIO);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_PISO);

		$criteria->addSelectColumn(ProveedorPeer::DIRECCION_DEPTO);

		$criteria->addSelectColumn(ProveedorPeer::LOCALIDAD_ID);

		$criteria->addSelectColumn(ProveedorPeer::PROVINCIA_ID);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProveedorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Proveedor
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ProveedorPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ProveedorPeer::populateObjects(ProveedorPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ProveedorPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Proveedor $value A Proveedor object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Proveedor $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Proveedor object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Proveedor) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Proveedor object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Proveedor Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ProveedorPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ProveedorPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ProveedorPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related ProveedorRubro table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinProveedorRubro(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProveedorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Localidad table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinLocalidad(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProveedorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Provincia table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinProvincia(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProveedorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with their ProveedorRubro objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinProveedorRubro(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);
		ProveedorRubroPeer::addSelectColumns($c);

		$c->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ProveedorRubroPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ProveedorRubroPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ProveedorRubroPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ProveedorRubroPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Proveedor) to $obj2 (ProveedorRubro)
				$obj2->addProveedor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with their Localidad objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinLocalidad(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);
		LocalidadPeer::addSelectColumns($c);

		$c->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = LocalidadPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = LocalidadPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					LocalidadPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Proveedor) to $obj2 (Localidad)
				$obj2->addProveedor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with their Provincia objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinProvincia(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);
		ProvinciaPeer::addSelectColumns($c);

		$c->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ProvinciaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ProvinciaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ProvinciaPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ProvinciaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Proveedor) to $obj2 (Provincia)
				$obj2->addProveedor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProveedorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
		$criteria->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);
		$criteria->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Proveedor objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol2 = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);

		ProveedorRubroPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ProveedorRubroPeer::NUM_COLUMNS - ProveedorRubroPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		ProvinciaPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (ProvinciaPeer::NUM_COLUMNS - ProvinciaPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
		$c->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);
		$c->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined ProveedorRubro rows

			$key2 = ProveedorRubroPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = ProveedorRubroPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ProveedorRubroPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ProveedorRubroPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Proveedor) to the collection in $obj2 (ProveedorRubro)
				$obj2->addProveedor($obj1);
			} // if joined row not null

			// Add objects for joined Localidad rows

			$key3 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = LocalidadPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					LocalidadPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Proveedor) to the collection in $obj3 (Localidad)
				$obj3->addProveedor($obj1);
			} // if joined row not null

			// Add objects for joined Provincia rows

			$key4 = ProvinciaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = ProvinciaPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = ProvinciaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					ProvinciaPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Proveedor) to the collection in $obj4 (Provincia)
				$obj4->addProveedor($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related ProveedorRubro table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptProveedorRubro(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Localidad table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptLocalidad(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Provincia table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptProvincia(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProveedorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
				$criteria->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseProveedorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with all related objects except ProveedorRubro.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptProveedorRubro(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol2 = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		ProvinciaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ProvinciaPeer::NUM_COLUMNS - ProvinciaPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);
				$c->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Localidad rows

				$key2 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = LocalidadPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					LocalidadPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj2 (Localidad)
				$obj2->addProveedor($obj1);

			} // if joined row is not null

				// Add objects for joined Provincia rows

				$key3 = ProvinciaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ProvinciaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ProvinciaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ProvinciaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj3 (Provincia)
				$obj3->addProveedor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with all related objects except Localidad.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptLocalidad(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol2 = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);

		ProveedorRubroPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ProveedorRubroPeer::NUM_COLUMNS - ProveedorRubroPeer::NUM_LAZY_LOAD_COLUMNS);

		ProvinciaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ProvinciaPeer::NUM_COLUMNS - ProvinciaPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
				$c->addJoin(array(ProveedorPeer::PROVINCIA_ID,), array(ProvinciaPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined ProveedorRubro rows

				$key2 = ProveedorRubroPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ProveedorRubroPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ProveedorRubroPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ProveedorRubroPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj2 (ProveedorRubro)
				$obj2->addProveedor($obj1);

			} // if joined row is not null

				// Add objects for joined Provincia rows

				$key3 = ProvinciaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ProvinciaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ProvinciaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ProvinciaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj3 (Provincia)
				$obj3->addProveedor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Proveedor objects pre-filled with all related objects except Provincia.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Proveedor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptProvincia(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		ProveedorPeer::addSelectColumns($c);
		$startcol2 = (ProveedorPeer::NUM_COLUMNS - ProveedorPeer::NUM_LAZY_LOAD_COLUMNS);

		ProveedorRubroPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ProveedorRubroPeer::NUM_COLUMNS - ProveedorRubroPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(ProveedorPeer::RUBRO_ID,), array(ProveedorRubroPeer::ID,), $join_behavior);
				$c->addJoin(array(ProveedorPeer::LOCALIDAD_ID,), array(LocalidadPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = ProveedorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = ProveedorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = ProveedorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				ProveedorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined ProveedorRubro rows

				$key2 = ProveedorRubroPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ProveedorRubroPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ProveedorRubroPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ProveedorRubroPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj2 (ProveedorRubro)
				$obj2->addProveedor($obj1);

			} // if joined row is not null

				// Add objects for joined Localidad rows

				$key3 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = LocalidadPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					LocalidadPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Proveedor) to the collection in $obj3 (Localidad)
				$obj3->addProveedor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return ProveedorPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Proveedor or Criteria object.
	 *
	 * @param      mixed $values Criteria or Proveedor object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseProveedorPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Proveedor object
		}

		if ($criteria->containsKey(ProveedorPeer::ID) && $criteria->keyContainsValue(ProveedorPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ProveedorPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseProveedorPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Proveedor or Criteria object.
	 *
	 * @param      mixed $values Criteria or Proveedor object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProveedorPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseProveedorPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ProveedorPeer::ID);
			$selectCriteria->add(ProveedorPeer::ID, $criteria->remove(ProveedorPeer::ID), $comparison);

		} else { // $values is Proveedor object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseProveedorPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseProveedorPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the proveedor table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ProveedorPeer::doOnDeleteCascade(new Criteria(ProveedorPeer::DATABASE_NAME), $con);
			ProveedorPeer::doOnDeleteSetNull(new Criteria(ProveedorPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(ProveedorPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Proveedor or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Proveedor object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ProveedorPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Proveedor) {
			// invalidate the cache for this single object
			ProveedorPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ProveedorPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				ProveedorPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ProveedorPeer::doOnDeleteCascade($criteria, $con);
			ProveedorPeer::doOnDeleteSetNull($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					ProveedorPeer::clearInstancePool();
				} else { // it's a PK or object
					ProveedorPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in NotaPedidoPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			NotaPedidoPeer::clearInstancePool();

			// invalidate objects in NotaPedidoPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			NotaPedidoPeer::clearInstancePool();

			// invalidate objects in CompraPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			CompraPeer::clearInstancePool();

			// invalidate objects in VentaPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			VentaPeer::clearInstancePool();

			// invalidate objects in RecepcionPedidoPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			RecepcionPedidoPeer::clearInstancePool();

			// invalidate objects in ProductoProveedorPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			ProductoProveedorPeer::clearInstancePool();

			// invalidate objects in ProveedorFDPPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			ProveedorFDPPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = ProveedorPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related NotaPedido objects
			$c = new Criteria(NotaPedidoPeer::DATABASE_NAME);
			
			$c->add(NotaPedidoPeer::PROVEEDOR_ID, $obj->getId());
			$affectedRows += NotaPedidoPeer::doDelete($c, $con);

			// delete related NotaPedido objects
			$c = new Criteria(NotaPedidoPeer::DATABASE_NAME);
			
			$c->add(NotaPedidoPeer::TRANSPORTE_ID, $obj->getId());
			$affectedRows += NotaPedidoPeer::doDelete($c, $con);

			// delete related Compra objects
			$c = new Criteria(CompraPeer::DATABASE_NAME);
			
			$c->add(CompraPeer::PROVEEDOR_ID, $obj->getId());
			$affectedRows += CompraPeer::doDelete($c, $con);

			// delete related Venta objects
			$c = new Criteria(VentaPeer::DATABASE_NAME);
			
			$c->add(VentaPeer::TRANSPORTISTA_EXTERNO_ID, $obj->getId());
			$affectedRows += VentaPeer::doDelete($c, $con);

			// delete related ProductoProveedor objects
			$c = new Criteria(ProductoProveedorPeer::DATABASE_NAME);
			
			$c->add(ProductoProveedorPeer::PROVEEDOR_ID, $obj->getId());
			$affectedRows += ProductoProveedorPeer::doDelete($c, $con);

			// delete related ProveedorFDP objects
			$c = new Criteria(ProveedorFDPPeer::DATABASE_NAME);
			
			$c->add(ProveedorFDPPeer::PROVEEDOR_ID, $obj->getId());
			$affectedRows += ProveedorFDPPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * This is a method for emulating ON DELETE SET NULL DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     void
	 */
	protected static function doOnDeleteSetNull(Criteria $criteria, PropelPDO $con)
	{

		// first find the objects that are implicated by the $criteria
		$objects = ProveedorPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {

			// set fkey col in related RecepcionPedido rows to NULL
			$selectCriteria = new Criteria(ProveedorPeer::DATABASE_NAME);
			$updateValues = new Criteria(ProveedorPeer::DATABASE_NAME);
			$selectCriteria->add(RecepcionPedidoPeer::TRANSPORTISTA_ID, $obj->getId());
			$updateValues->add(RecepcionPedidoPeer::TRANSPORTISTA_ID, null);

					BasePeer::doUpdate($selectCriteria, $updateValues, $con); // use BasePeer because generated Peer doUpdate() methods only update using pkey

		}
	}

	/**
	 * Validates all modified columns of given Proveedor object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Proveedor $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Proveedor $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ProveedorPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ProveedorPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(ProveedorPeer::DATABASE_NAME, ProveedorPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = ProveedorPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Proveedor
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ProveedorPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ProveedorPeer::DATABASE_NAME);
		$criteria->add(ProveedorPeer::ID, $pk);

		$v = ProveedorPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ProveedorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ProveedorPeer::DATABASE_NAME);
			$criteria->add(ProveedorPeer::ID, $pks, Criteria::IN);
			$objs = ProveedorPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseProveedorPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the ProveedorPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the ProveedorPeer class:
//
// Propel::getDatabaseMap(ProveedorPeer::DATABASE_NAME)->addTableBuilder(ProveedorPeer::TABLE_NAME, ProveedorPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseProveedorPeer::DATABASE_NAME)->addTableBuilder(BaseProveedorPeer::TABLE_NAME, BaseProveedorPeer::getMapBuilder());

